export const todrive = {
  quantity: '(1)',
  day: 'Sunday,',
  date: '26 March 2023',
  code: 'W7DE6M4D',
  time: '23:25',
  location1firstname: 'Maashaven South side',
  location1secondname: 'Rotterdam',
  time2: '00:32',
  location2firstname: 'Kadijk',
  location2secondname: 'Kadijk',
  distance: '85,7 km. 1 hour, 7 min',
  pessanger: '8 Passengers',
  bag: 'No Luggage',
  comment: 'No comments',
  distance2: 'No comments',
  phone: 'No comments',
  price: '140,55',
};

export const driven = {
  quantity: '(1)',
  day: 'Wednesday, ',
  date: '1 March 2023',
  code: 'ECXA17R9',
  time: '10:00',
  location1firstname: 'Stadvliedt',
  location1secondname: 'Dordrecht',
  time2: '11:32',
  location2firstname: 'Evert van de beekstraat',
  location2secondname: 'Schiphol',
  distance: '85,7 km. 1 hour, 7 min',
  pessanger: '8 Passengers',
  bag: 'No Luggage',
  comment: 'No comments',
  price: '91.35',
};

export const canceled = {
  quantity: '(1)',
  day: 'Friday, ',
  date: '13 January 2023',
  code: '7T22JNNZ',
  time: '10:00',
  location1firstname: 'Bergstoep',
  location1secondname: 'Rotterdam',
  time2: '11:32',
  location2firstname: 'Evert van de beekstraat',
  location2secondname: 'Schiphol',
  distance: '75,6 km. 51 min',
  pessanger: '5 Passengers',
  bag: '5 Pieces of small hold luggage',
  comment:
    'Please note that this must be done at the same time as the order number48WYVYSV. A total of 11 personsmust be transported',
  price: '91.35',
  type: 'Canceled, ',
  canceldate: 'January 12, 2023',
};
